#!/bin/bash

for f in $(git status -u | grep "7z-data/"); do
    echo "==> Adding: $f"
    git add "$f"
    git commit -m "Added $f"
    git push --progress -v
    echo "*** Done ***"
done

git add 7z-data/sha256sum.txt
git commit -m "added 7z-data/sha256sum.txt"
git push
